hard_tabs = true
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 20
use_field_init_shorthand = true
